-- =============================================
-- Migración 058: Catálogos MH — Sectores Económicos
-- Basado en CAT-019 del Ministerio de Hacienda de El Salvador
-- =============================================

CREATE TABLE IF NOT EXISTS sectores_economicos (
  codigo    VARCHAR(6) PRIMARY KEY,
  nombre    VARCHAR(300) NOT NULL
);

INSERT INTO sectores_economicos (codigo, nombre) VALUES
  ('A0111', 'Cultivo de cereales, legumbres y semillas oleaginosas'),
  ('A0112', 'Cultivo de hortalizas, raíces y tubérculos'),
  ('A0113', 'Cultivo de frutas tropicales y subtropicales'),
  ('A0114', 'Cultivo de café'),
  ('A0115', 'Cultivo de caña de azúcar'),
  ('A0119', 'Otros cultivos no perennes'),
  ('A0121', 'Cultivo de frutas de pepita y hueso'),
  ('A0122', 'Cultivo de frutos oleaginosos'),
  ('A0130', 'Propagación de plantas'),
  ('A0141', 'Cría de ganado bovino'),
  ('A0142', 'Cría de ganado porcino'),
  ('A0143', 'Cría de aves de corral'),
  ('A0149', 'Cría de otros animales'),
  ('A0150', 'Cultivo de productos agrícolas combinado con cría de animales'),
  ('A0161', 'Actividades de apoyo a la agricultura'),
  ('A0162', 'Actividades de apoyo a la ganadería'),
  ('A0170', 'Caza, trampas y actividades de servicios conexos'),
  ('A0210', 'Silvicultura y otras actividades forestales'),
  ('A0220', 'Extracción de madera'),
  ('A0230', 'Recolección de productos forestales no madereros'),
  ('A0311', 'Pesca marítima'),
  ('A0312', 'Pesca de agua dulce'),
  ('A0321', 'Cultivo de peces en criaderos'),
  ('A0322', 'Cultivo de camarones y langostinos'),
  ('B0710', 'Extracción de minerales de hierro'),
  ('B0721', 'Extracción de minerales de metales preciosos'),
  ('B0810', 'Extracción de piedra, arena y arcilla'),
  ('B0891', 'Extracción de minerales para productos químicos y fertilizantes'),
  ('B0892', 'Extracción de sal'),
  ('B0899', 'Otras actividades de explotación de minas y canteras n.c.p.'),
  ('C1010', 'Procesamiento y conservación de carne'),
  ('C1020', 'Procesamiento y conservación de pescado, crustáceos y moluscos'),
  ('C1030', 'Procesamiento y conservación de frutas, legumbres y hortalizas'),
  ('C1040', 'Elaboración de aceites y grasas de origen vegetal y animal'),
  ('C1050', 'Elaboración de productos lácteos'),
  ('C1061', 'Molienda de cereales'),
  ('C1062', 'Elaboración de productos de panadería y pastelería'),
  ('C1071', 'Elaboración y refinación de azúcar'),
  ('C1072', 'Elaboración de confites y golosinas'),
  ('C1074', 'Elaboración de productos de panadería y repostería'),
  ('C1079', 'Elaboración de otros productos alimenticios n.c.p.'),
  ('C1080', 'Elaboración de alimentos preparados para animales'),
  ('C1101', 'Destilación, rectificación y mezcla de bebidas alcohólicas'),
  ('C1102', 'Elaboración de vinos'),
  ('C1103', 'Elaboración de bebidas malteadas y cerveza'),
  ('C1104', 'Elaboración de bebidas no alcohólicas y aguas minerales'),
  ('C1105', 'Elaboración de productos de tabaco'),
  ('C1311', 'Preparación e hilado de fibras textiles'),
  ('C1312', 'Tejedura de productos textiles'),
  ('C1410', 'Fabricación de prendas de vestir, excepto prendas de piel'),
  ('C1420', 'Fabricación de artículos de piel'),
  ('C1430', 'Fabricación de artículos de punto y ganchillo'),
  ('C1511', 'Curtido y adobo de cueros'),
  ('C1520', 'Fabricación de calzado'),
  ('C1610', 'Aserradero y acepilladura de madera'),
  ('C1621', 'Fabricación de hojas de madera para enchapado y tableros'),
  ('C1622', 'Fabricación de partes y piezas de carpintería'),
  ('C1623', 'Fabricación de recipientes de madera'),
  ('C1701', 'Fabricación de pasta de madera, papel y cartón'),
  ('C1702', 'Fabricación de papel y cartón ondulado'),
  ('C1709', 'Fabricación de otros artículos de papel y cartón'),
  ('C1811', 'Impresión de periódicos, revistas y otras publicaciones periódicas'),
  ('C1812', 'Otras actividades de impresión'),
  ('C1910', 'Fabricación de productos de hornos de coque'),
  ('C1920', 'Fabricación de productos de la refinación del petróleo'),
  ('C2011', 'Fabricación de sustancias químicas básicas'),
  ('C2012', 'Fabricación de abonos y compuestos de nitrógeno'),
  ('C2021', 'Fabricación de plaguicidas y otros productos químicos de uso agropecuario'),
  ('C2023', 'Fabricación de jabones, detergentes y preparados de tocador'),
  ('C2029', 'Fabricación de otros productos químicos n.c.p.'),
  ('C2100', 'Fabricación de productos farmacéuticos, sustancias químicas medicinales y productos botánicos'),
  ('C2211', 'Fabricación de cubiertas y cámaras de caucho'),
  ('C2219', 'Fabricación de otros productos de caucho'),
  ('C2220', 'Fabricación de productos de plástico'),
  ('C2310', 'Fabricación de vidrio y productos de vidrio'),
  ('C2391', 'Fabricación de productos de porcelana y cerámica'),
  ('C2392', 'Fabricación de materiales de construcción de arcilla'),
  ('C2393', 'Fabricación de cemento, cal y yeso'),
  ('C2394', 'Fabricación de artículos de hormigón, cemento y yeso'),
  ('C2410', 'Industrias básicas de hierro y acero'),
  ('C2420', 'Fabricación de productos primarios de metales preciosos y no ferrosos'),
  ('C2511', 'Fabricación de productos metálicos para uso estructural'),
  ('C2512', 'Fabricación de tanques, depósitos y recipientes de metal'),
  ('C2591', 'Forja, prensado, estampado y laminado de metales'),
  ('C2592', 'Tratamiento y revestimiento de metales'),
  ('C2599', 'Fabricación de otros productos elaborados de metal n.c.p.'),
  ('C2610', 'Fabricación de componentes y tableros electrónicos'),
  ('C2620', 'Fabricación de ordenadores y equipo periférico'),
  ('C2630', 'Fabricación de equipo de comunicaciones'),
  ('C2640', 'Fabricación de aparatos electrónicos de consumo'),
  ('C2710', 'Fabricación de motores, generadores y transformadores eléctricos'),
  ('C2720', 'Fabricación de pilas, baterías y acumuladores'),
  ('C2731', 'Fabricación de cables de fibra óptica'),
  ('C2732', 'Fabricación de otros hilos y cables eléctricos'),
  ('C2740', 'Fabricación de equipo eléctrico de iluminación'),
  ('C2811', 'Fabricación de motores y turbinas'),
  ('C2817', 'Fabricación de maquinaria de oficina'),
  ('C2825', 'Fabricación de maquinaria para la elaboración de alimentos, bebidas y tabaco'),
  ('C3100', 'Fabricación de muebles'),
  ('C3211', 'Fabricación de joyas y artículos conexos'),
  ('C3220', 'Fabricación de instrumentos musicales'),
  ('C3230', 'Fabricación de artículos de deporte'),
  ('C3240', 'Fabricación de juegos y juguetes'),
  ('C3250', 'Fabricación de instrumentos y materiales médicos y odontológicos'),
  ('D3511', 'Generación de energía eléctrica'),
  ('D3512', 'Transmisión de energía eléctrica'),
  ('D3513', 'Distribución de energía eléctrica'),
  ('D3520', 'Fabricación de gas; distribución de combustibles gaseosos por tuberías'),
  ('D3530', 'Suministro de vapor y aire acondicionado'),
  ('E3600', 'Captación, tratamiento y distribución de agua'),
  ('E3700', 'Evacuación de aguas residuales'),
  ('E3811', 'Recolección de desechos no peligrosos'),
  ('E3812', 'Recolección de desechos peligrosos'),
  ('E3821', 'Tratamiento y eliminación de desechos no peligrosos'),
  ('E3822', 'Tratamiento y eliminación de desechos peligrosos'),
  ('E3830', 'Recuperación de materiales'),
  ('E3900', 'Actividades de saneamiento y otros servicios de gestión de desechos'),
  ('F4100', 'Construcción de edificios'),
  ('F4210', 'Construcción de carreteras y vías de ferrocarril'),
  ('F4220', 'Construcción de proyectos de servicio público'),
  ('F4290', 'Construcción de otras obras de ingeniería civil'),
  ('F4311', 'Demolición'),
  ('F4312', 'Preparación del terreno'),
  ('F4321', 'Instalaciones eléctricas'),
  ('F4322', 'Instalaciones de fontanería, calefacción y aire acondicionado'),
  ('F4330', 'Terminación y acabado de edificios'),
  ('F4390', 'Otras actividades especializadas de construcción'),
  ('G4510', 'Venta de vehículos automotores'),
  ('G4520', 'Mantenimiento y reparación de vehículos automotores'),
  ('G4530', 'Venta de partes, piezas y accesorios de vehículos automotores'),
  ('G4540', 'Venta, mantenimiento y reparación de motocicletas, sus partes, piezas y accesorios'),
  ('G4610', 'Venta al por mayor a cambio de una retribución o por contrata'),
  ('G4620', 'Venta al por mayor de materias primas agropecuarias y animales vivos'),
  ('G4630', 'Venta al por mayor de alimentos, bebidas y tabaco'),
  ('G4641', 'Venta al por mayor de productos textiles y calzado'),
  ('G4649', 'Venta al por mayor de otros enseres domésticos'),
  ('G4651', 'Venta al por mayor de ordenadores, equipo periférico y programas informáticos'),
  ('G4652', 'Venta al por mayor de equipo electrónico y de telecomunicaciones'),
  ('G4661', 'Venta al por mayor de maquinaria agropecuaria'),
  ('G4669', 'Venta al por mayor de otra maquinaria y equipo'),
  ('G4690', 'Venta al por mayor no especializada'),
  ('G4711', 'Venta al por menor en comercios no especializados con predominio de alimentos'),
  ('G4719', 'Venta al por menor en otros comercios no especializados'),
  ('G4721', 'Venta al por menor de alimentos en comercios especializados'),
  ('G4722', 'Venta al por menor de bebidas en comercios especializados'),
  ('G4730', 'Venta al por menor de combustibles para automotores en comercios especializados'),
  ('G4741', 'Venta al por menor de computadoras, equipo periférico y programas informáticos'),
  ('G4742', 'Venta al por menor de equipo de telecomunicaciones'),
  ('G4751', 'Venta al por menor de productos textiles en comercios especializados'),
  ('G4759', 'Venta al por menor de otros enseres domésticos en comercios especializados'),
  ('G4761', 'Venta al por menor de libros, periódicos y artículos de papelería'),
  ('G4762', 'Venta al por menor de música y películas grabadas'),
  ('G4771', 'Venta al por menor de prendas de vestir, calzado y artículos de cuero'),
  ('G4772', 'Venta al por menor de productos farmacéuticos y medicinales'),
  ('G4773', 'Venta al por menor de artículos médicos y ortopédicos'),
  ('G4774', 'Venta al por menor de cosméticos y artículos de tocador'),
  ('G4781', 'Venta al por menor de alimentos, bebidas y tabaco en puestos de venta y mercados'),
  ('G4782', 'Venta al por menor de productos textiles, prendas de vestir y calzado en puestos de venta'),
  ('G4789', 'Venta al por menor de otros productos en puestos de venta y mercados'),
  ('G4791', 'Venta al por menor por correo y por internet'),
  ('G4799', 'Otras actividades de venta al por menor no realizadas en comercios, puestos de venta o mercados'),
  ('H4911', 'Transporte interurbano de pasajeros por ferrocarril'),
  ('H4912', 'Transporte de carga por ferrocarril'),
  ('H4921', 'Transporte urbano y suburbano de pasajeros por vía terrestre'),
  ('H4922', 'Otros tipos de transporte de pasajeros por vía terrestre'),
  ('H4923', 'Transporte de carga por carretera'),
  ('H4930', 'Transporte por tuberías'),
  ('H5011', 'Transporte de pasajeros marítimo y de cabotaje'),
  ('H5012', 'Transporte de carga marítimo y de cabotaje'),
  ('H5021', 'Transporte de pasajeros por vías de navegación interiores'),
  ('H5022', 'Transporte de carga por vías de navegación interiores'),
  ('H5110', 'Transporte aéreo de pasajeros'),
  ('H5120', 'Transporte aéreo de carga'),
  ('H5210', 'Almacenamiento y depósito'),
  ('H5221', 'Actividades de servicios vinculadas al transporte terrestre'),
  ('H5222', 'Actividades de servicios vinculadas al transporte acuático'),
  ('H5223', 'Actividades de servicios vinculadas al transporte aéreo'),
  ('H5224', 'Manipulación de carga'),
  ('H5229', 'Otras actividades de apoyo al transporte'),
  ('H5310', 'Actividades postales nacionales'),
  ('H5320', 'Actividades de mensajería'),
  ('I5510', 'Actividades de alojamiento para estancias cortas'),
  ('I5520', 'Actividades de campamentos, parques de vehículos recreativos y parques de caravanas'),
  ('I5590', 'Otras actividades de alojamiento'),
  ('I5610', 'Actividades de restaurantes y de servicio móvil de comidas'),
  ('I5621', 'Suministro de comidas por encargo para eventos'),
  ('I5629', 'Otras actividades de servicio de comidas'),
  ('I5630', 'Actividades de servicio de bebidas'),
  ('J5811', 'Edición de libros'),
  ('J5812', 'Edición de directorios y listas de correo'),
  ('J5813', 'Edición de periódicos, revistas y otras publicaciones periódicas'),
  ('J5819', 'Otras actividades de edición'),
  ('J5820', 'Edición de programas informáticos'),
  ('J5911', 'Actividades de producción de películas cinematográficas, videos y programas de televisión'),
  ('J5912', 'Actividades de postproducción de películas'),
  ('J5913', 'Actividades de distribución de películas cinematográficas, videos y programas de televisión'),
  ('J5914', 'Actividades de exhibición de películas cinematográficas y cintas de video'),
  ('J5920', 'Actividades de grabación de sonido y edición de música'),
  ('J6010', 'Transmisión de radio'),
  ('J6020', 'Programación y transmisión de televisión'),
  ('J6110', 'Actividades de telecomunicaciones alámbricas'),
  ('J6120', 'Actividades de telecomunicaciones inalámbricas'),
  ('J6130', 'Actividades de telecomunicaciones por satélite'),
  ('J6190', 'Otras actividades de telecomunicaciones'),
  ('J6201', 'Programación informática'),
  ('J6202', 'Consultoría de informática y gestión de instalaciones informáticas'),
  ('J6209', 'Otras actividades de tecnología de la información y servicios informáticos'),
  ('J6311', 'Procesamiento de datos, hospedaje y actividades conexas'),
  ('J6312', 'Portales web'),
  ('J6391', 'Actividades de agencias de noticias'),
  ('J6399', 'Otras actividades de servicios de información n.c.p.'),
  ('K6411', 'Banca central'),
  ('K6419', 'Otros tipos de intermediación monetaria'),
  ('K6420', 'Actividades de sociedades de cartera'),
  ('K6430', 'Fideicomisos, fondos y otras fuentes financieras similares'),
  ('K6491', 'Arrendamiento financiero'),
  ('K6492', 'Otras actividades de concesión de crédito'),
  ('K6499', 'Otras actividades de servicios financieros, excepto las de seguros y fondos de pensiones'),
  ('K6511', 'Seguros de vida'),
  ('K6512', 'Seguros generales'),
  ('K6520', 'Reaseguros'),
  ('K6530', 'Fondos de pensiones'),
  ('K6611', 'Administración de mercados financieros'),
  ('K6612', 'Corretaje de valores y contratos de comisiones'),
  ('K6619', 'Otras actividades auxiliares de servicios financieros n.c.p.'),
  ('K6621', 'Actividades de evaluación de riesgos y daños'),
  ('K6622', 'Actividades de agentes y corredores de seguros'),
  ('K6629', 'Otras actividades auxiliares de seguros y fondos de pensiones'),
  ('K6630', 'Actividades de gestión de fondos'),
  ('L6810', 'Actividades inmobiliarias realizadas con bienes propios o arrendados'),
  ('L6820', 'Actividades inmobiliarias realizadas a cambio de una retribución o por contrata'),
  ('M6910', 'Actividades jurídicas'),
  ('M6920', 'Actividades de contabilidad, teneduría de libros, auditoría y asesoría fiscal'),
  ('M7010', 'Actividades de oficinas principales'),
  ('M7020', 'Actividades de consultoría de gestión'),
  ('M7110', 'Actividades de arquitectura e ingeniería y actividades conexas de consultoría técnica'),
  ('M7120', 'Ensayos y análisis técnicos'),
  ('M7210', 'Investigación y desarrollo experimental en ciencias naturales e ingeniería'),
  ('M7220', 'Investigación y desarrollo experimental en ciencias sociales y humanidades'),
  ('M7310', 'Publicidad'),
  ('M7320', 'Estudio de mercado y realización de sondeos de opinión pública'),
  ('M7410', 'Actividades especializadas de diseño'),
  ('M7420', 'Actividades de fotografía'),
  ('M7490', 'Otras actividades profesionales, científicas y técnicas n.c.p.'),
  ('M7500', 'Actividades veterinarias'),
  ('N7710', 'Alquiler de vehículos automotores'),
  ('N7721', 'Alquiler de equipo recreativo y deportivo'),
  ('N7722', 'Alquiler de cintas de video y discos'),
  ('N7729', 'Alquiler de otros efectos personales y enseres domésticos'),
  ('N7730', 'Alquiler de otros tipos de maquinaria, equipo y bienes tangibles'),
  ('N7740', 'Arrendamiento de propiedad intelectual y productos similares, excepto obras protegidas por derechos de autor'),
  ('N7810', 'Actividades de agencias de colocación de empleo'),
  ('N7820', 'Actividades de agencias de empleo temporal'),
  ('N7830', 'Dotación de otros recursos humanos'),
  ('N7911', 'Actividades de agencias de viajes'),
  ('N7912', 'Actividades de operadores turísticos'),
  ('N7990', 'Otros servicios de reservas y actividades conexas'),
  ('N8010', 'Actividades de seguridad privada'),
  ('N8020', 'Actividades de servicios de sistemas de seguridad'),
  ('N8030', 'Actividades de investigación'),
  ('N8110', 'Actividades combinadas de apoyo a edificios e instalaciones'),
  ('N8121', 'Limpieza general de edificios'),
  ('N8129', 'Otras actividades de limpieza de edificios e instalaciones industriales'),
  ('N8130', 'Actividades de servicio de paisajismo y mantenimiento de jardines'),
  ('N8211', 'Actividades combinadas de servicios administrativos de oficina'),
  ('N8219', 'Fotocopiado, preparación de documentos y otras actividades especializadas de apoyo de oficina'),
  ('N8220', 'Actividades de centros de llamadas'),
  ('N8230', 'Organización de convenciones y exposiciones comerciales'),
  ('N8291', 'Actividades de agencias de cobro y oficinas de calificación crediticia'),
  ('N8292', 'Actividades de envasado y empaque'),
  ('N8299', 'Otras actividades de servicios de apoyo a las empresas n.c.p.'),
  ('O8411', 'Actividades de la administración pública en general'),
  ('O8412', 'Regulación de las actividades de organismos que prestan servicios sanitarios, educativos, culturales y otros servicios sociales'),
  ('O8413', 'Regulación y facilitación de la actividad económica'),
  ('P8510', 'Enseñanza preescolar y primaria'),
  ('P8521', 'Enseñanza secundaria de formación general'),
  ('P8522', 'Enseñanza secundaria de formación técnica y profesional'),
  ('P8530', 'Enseñanza superior'),
  ('P8541', 'Enseñanza deportiva y recreativa'),
  ('P8542', 'Enseñanza cultural'),
  ('P8549', 'Otros tipos de enseñanza n.c.p.'),
  ('P8550', 'Actividades de apoyo a la enseñanza'),
  ('Q8610', 'Actividades de hospitales'),
  ('Q8620', 'Actividades de práctica médica y odontológica'),
  ('Q8690', 'Otras actividades de atención de la salud humana'),
  ('Q8710', 'Actividades de atención de enfermería en instituciones'),
  ('Q8720', 'Actividades de atención a personas con discapacidad y trastornos mentales'),
  ('Q8730', 'Actividades de atención a personas de edad avanzada en instituciones'),
  ('Q8790', 'Otras actividades de atención en instituciones'),
  ('Q8810', 'Actividades de servicios sociales sin alojamiento para personas de edad avanzada y discapacitadas'),
  ('Q8890', 'Otras actividades de servicios sociales sin alojamiento'),
  ('R9000', 'Actividades creativas, artísticas y de entretenimiento'),
  ('R9101', 'Actividades de bibliotecas y archivos'),
  ('R9102', 'Actividades de museos y gestión de lugares y edificios históricos'),
  ('R9200', 'Actividades de juegos de azar y apuestas'),
  ('R9311', 'Actividades de parques de atracciones y parques temáticos'),
  ('R9312', 'Actividades de clubes deportivos'),
  ('R9319', 'Otras actividades deportivas'),
  ('R9321', 'Actividades de parques de atracciones y parques temáticos'),
  ('R9329', 'Otras actividades de esparcimiento y recreativas n.c.p.'),
  ('S9411', 'Actividades de asociaciones empresariales y de empleadores'),
  ('S9412', 'Actividades de asociaciones profesionales'),
  ('S9420', 'Actividades de sindicatos'),
  ('S9491', 'Actividades de organizaciones religiosas'),
  ('S9492', 'Actividades de organizaciones políticas'),
  ('S9499', 'Actividades de otras asociaciones n.c.p.'),
  ('S9511', 'Reparación de computadoras y equipo periférico'),
  ('S9512', 'Reparación de equipo de comunicaciones'),
  ('S9521', 'Reparación de aparatos electrónicos de consumo'),
  ('S9522', 'Reparación de electrodomésticos y equipo de jardinería y uso doméstico'),
  ('S9523', 'Reparación de calzado y artículos de cuero'),
  ('S9524', 'Reparación de muebles y accesorios domésticos'),
  ('S9525', 'Reparación de relojes y joyas'),
  ('S9529', 'Reparación de otros efectos personales y enseres domésticos'),
  ('S9600', 'Otras actividades de servicios personales'),
  ('T9700', 'Actividades de los hogares como empleadores de personal doméstico'),
  ('T9810', 'Actividades no diferenciadas de producción de bienes de los hogares privados para uso propio'),
  ('T9820', 'Actividades no diferenciadas de producción de servicios de los hogares privados para uso propio'),
  ('U9900', 'Actividades de organizaciones y órganos extraterritoriales')
ON CONFLICT (codigo) DO NOTHING;

-- =============================================
-- FIN DE MIGRACIÓN
-- =============================================
