import { Router } from 'express';
import { autenticar } from '../../shared/middlewares/auth.middleware.js';
import resumenEndpoint from './resumen/endpoint.js';
import productosEndpoint from './productos/endpoint.js';
import movimientosListar from './movimientos/listar/endpoint.js';
import movimientosCrear from './movimientos/crear/endpoint.js';
import movimientosRevertir from './movimientos/revertir/endpoint.js';
import reconciliarEndpoint from './reconciliar/endpoint.js';
import consumirReceta from './consumir-receta/endpoint.js';
import kardexEndpoint from './kardex/endpoint.js';
import sesionesCrear from './sesiones/crear/endpoint.js';
import sesionesListar from './sesiones/listar/endpoint.js';
import sesionesDetalle from './sesiones/detalle/endpoint.js';
import sesionesConteo from './sesiones/conteo/endpoint.js';
import sesionesEliminarConteo from './sesiones/eliminar-conteo/endpoint.js';
import sesionesCerrar from './sesiones/cerrar/endpoint.js';
import sesionesCancelar from './sesiones/cancelar/endpoint.js';

const router = Router({ mergeParams: true });
router.use(autenticar);
router.use(resumenEndpoint);
router.use(productosEndpoint);
router.use(movimientosListar);
router.use(movimientosCrear);
router.use(movimientosRevertir);
router.use(reconciliarEndpoint);
router.use(consumirReceta);
router.use(kardexEndpoint);
router.use(sesionesCrear);
router.use(sesionesListar);
router.use(sesionesDetalle);
router.use(sesionesConteo);
router.use(sesionesEliminarConteo);
router.use(sesionesCerrar);
router.use(sesionesCancelar);

export default router;
