import { Router } from 'express';
import { autenticar } from '../../shared/middlewares/auth.middleware.js';
import mesasListar from './mesas/listar/endpoint.js';
import mesasObtener from './mesas/obtener/endpoint.js';
import mesasCrear from './mesas/crear/endpoint.js';
import mesasActualizar from './mesas/actualizar/endpoint.js';
import ordenesListar from './ordenes/listar/endpoint.js';
import ordenesObtener from './ordenes/obtener/endpoint.js';
import ordenesCrear from './ordenes/crear/endpoint.js';
import ordenesActualizar from './ordenes/actualizar/endpoint.js';
import ordenesCambiarEstado from './ordenes/cambiar-estado/endpoint.js';
import ordenesPropina from './ordenes/propina/endpoint.js';
import ordenesAgregarItem from './ordenes/agregar-item/endpoint.js';
import ordenesActualizarItem from './ordenes/actualizar-item/endpoint.js';
import ordenesEliminarItem from './ordenes/eliminar-item/endpoint.js';
import ordenesSplit from './ordenes/split/endpoint.js';
import ordenesTransferir from './ordenes/transferir/endpoint.js';
import ordenesCambiarMesa from './ordenes/cambiar-mesa/endpoint.js';
import ordenesPagar from './ordenes/pagar/endpoint.js';

const router = Router({ mergeParams: true });
router.use(autenticar);
router.use(mesasListar);
router.use(mesasObtener);
router.use(mesasCrear);
router.use(mesasActualizar);
router.use(ordenesListar);
router.use(ordenesObtener);
router.use(ordenesCrear);
router.use(ordenesActualizar);
router.use(ordenesCambiarEstado);
router.use(ordenesPropina);
router.use(ordenesAgregarItem);
router.use(ordenesActualizarItem);
router.use(ordenesEliminarItem);
router.use(ordenesSplit);
router.use(ordenesTransferir);
router.use(ordenesCambiarMesa);
router.use(ordenesPagar);

export default router;
